# Generated by Django 5.2.17 on 2026-09-25 19:47

import django.contrib.postgres.fields
import django.db.models.deletion
import forms_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(default=forms_app.models.generate_token, editable=False, max_length=32, unique=True)),
                ('allowed_origins', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('spam_action', models.CharField(choices=[('flag', 'Flag'), ('drop', 'Drop')], default='flag', max_length=10)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('spam_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ham', 'Ham'), ('spam', 'Spam')], max_length=10)),
                ('corrected', models.BooleanField(default=False)),
                ('source_ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_app.form')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='spam.modelversion')),
            ],
            options={
                'indexes': [models.Index(fields=['form', '-created_at'], name='forms_app_s_form_id_e10c4e_idx'), models.Index(fields=['form', 'status', '-created_at'], name='forms_app_s_form_id_2a01ba_idx')],
            },
        ),
    ]
