# Generated by Django 5.2.17 on 2026-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_submission_spam_signals'),
        ('spam', '0002_modelversion_threshold_sha256_sklearn_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['notification_status', 'created_at'], name='forms_app_s_notific_edfd09_idx'),
        ),
    ]
